config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  get 'comments/destroy'
  root 'static_pages#home'
  get '/home',      to: 'static_pages#home', as: 'home'
  get '/help',      to: 'static_pages#help', as: 'help'
  get '/signup',    to: 'users#new'
  post '/signup',   to: 'users#create'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :comments,      only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :entries
  resources :users do
    member do
      get :following, :followers
    end
  end

  namespace :api do
    namespace :v1 do
      resources :entries
    end
  end
end

app/views/shared/_comment.html.erb
<% if @cmt_items.any? %>
  <div class="row">
    <ol class="microposts">
      <%= render @cmt_items %>
    </ol>
    <div class="pull-right">
      <%= will_paginate @cmt_items %>
    </div>
  </div>
<% end %>

app/views/shared/_enry_update_form.html.erb
<%= form_for @entry  do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.label t "entries.create.title" %>
    <%= f.text_field :title, class: "form-control" %>

    <%= f.label t "entries.create.content" %>
    <%= f.text_area :content, placeholder: t("entries.create.text_area_holder"),
      class: "entry_content form-control" %>
  </div>
  <%= f.submit @btn_submit, class: "btn btn-primary" %>
<% end %>

app/views/shared/_entry.html.erb
<div class="title_entry">
  <h3><%= @entry.title.titleize %></h3>
</div>
<div class="time_entry">
  <i class="fa fa-calendar"></i>
  <%= @entry.created_at.strftime Settings.DATE_TIME_FORMAT %>
  <% if admin? || current_user?(@entry.user) %>
    <%= link_to t("entries.delete.link_delete"), @entry, method: :delete,
      class: "btn btn-xs btn-danger pull-right btn-delete",
      data: { confirm: t("common.delete_confirmation", item: :entry) } %>
      <%= link_to t("entries.edit.link_edit"), edit_entry_path,
      class: "btn btn-xs btn-warning pull-right" %>
  <% end %>
</div>
<div class="content_entry">
  <p>
    <%= simple_format @entry.content %>
  </p>
  <p class="text-right">
    <%= @entry.user.name.titleize %>.
  </p>
</div>

app/views/shared/_entry_form.html.erb
<%= form_for @entry  do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.label t "entries.create.title" %>
    <%= f.text_field :title, class: "form-control" %>

    <%= f.label t "entries.create.content" %>
    <%= f.text_area :content, placeholder: t("entries.create.text_area_holder"),
      class: "entry_content form-control" %>
  </div>
  <% if logged_in? %>
    <%= f.submit "Post", class: "btn btn-primary" %>
  <% else %>
    <%= f.submit "Post", class: "btn btn-primary", disabled: true %>
  <% end %>
<% end %>

app/views/shared/_entry_user.html.erb
<% if @entries.any? %>
  <ol class="microposts">
    <%= render @entries %>
  </ol>
  <div class="text-center">
    <%= will_paginate @entries %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any?%>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "common.error_msg" %>
      <%= pluralize object.errors.count, t("common.error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <div class="text-center">
    <%= will_paginate @feed_items %>
  </div>
<% end %>

app/views/shared/_follow.html.erb
<%= form_for current_user.active_relationships.build, remote: true do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit t("entries.show.btn_follow"), class: "btn btn-primary" %>
<% end %>

app/views/shared/_follow_form.html.erb
<% unless current_user? @user %>
  <div id="follow_form">
    <% if current_user.following? @user %>
      <%= render "shared/unfollow" %>
    <% else %>
      <%= render "shared/follow" %>
    <% end %>
  </div>
<% end %>

app/views/shared/_guest.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="alert alert-info">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>
      <%= link_to t("entries.index.msg_log_in_1"), login_path %>
      <%= t "entries.index.msg_log_in_2" %>
      <%= link_to t("entries.index.msg_log_in_3"), login_path %>
      <%= t "entries.index.msg_log_in_4" %>
    </strong>
  </div>
  <h3><%= t "entries.index.header" %></h3>
  <%= render "shared/feed" %>
</div>

<script>
  $(document).ready(function(){
    SHOW_TIME = 5000;
    FADE_TIME = 500;
    $(".alert-info").fadeTo(SHOW_TIME, FADE_TIME).slideUp(FADE_TIME, function(){
      $(".alert-info").slideUp(FADE_TIME);
    });
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= user_url @user %>">
    <strong id="entries" class="stat">
      <%= @user.entries.count %>
    </strong>
    <%= t "entries.show.entries_count" %>
  </a>
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    <%= t "entries.show.lb_following" %>
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= t "entries.show.lb_follower" %>
  </a>
</div>

app/views/shared/_unfollow.html.erb
<%= form_for current_user.active_relationships.find_by(followed_id: @user.id),
  html: { method: :delete },
  remote: true do |f| %>
  <%= f.submit t("entries.show.btn_unfollow"), class: "btn" %>
<% end %>

app/views/shared/_user_home.html.erb
<aside class="col-md-4">
  <section class="user_info">
    <h1><a href="<%= user_url @user %>">
        <%= gravatar_for @user %>
        <%= @user.name %>
    </a></h1>
    <%= render "shared/stats" %>
    <%= render "shared/entry_form" %>
</aside>
<div class="col-md-8">
  <h3><%= t "entries.index.header" %></h3>
  <%= render "shared/feed" %>
</div>

app/views/shared/_user_info.html.erb
<section class="user_info">
  <h1>
    <a href="<%= user_url @user %>">
      <%= gravatar_for @user %>
      <%= @user.name %>
    </a>
  </h1>
  <%= render "shared/stats" %>
</section>
<section>
  <%= render "shared/follow_form" if logged_in? %>
</section>