config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  get 'comments/destroy'
  root 'static_pages#home'
  get '/home',      to: 'static_pages#home', as: 'home'
  get '/help',      to: 'static_pages#help', as: 'help'
  get '/signup',    to: 'users#new'
  post '/signup',   to: 'users#create'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :comments,      only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :entries
  resources :users do
    member do
      get :following, :followers
    end
  end

  namespace :api do
    namespace :v1 do
      resources :entries
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Tiny Blog</a>
    by <strong><a href="https://github.com/FramgiaInternship/tiny_blog">Son Tran</a></strong>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("static_pages.footer.about"), "#" %></li>
      <li><%= link_to t("static_pages.footer.contact"), "#" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("static_pages.header.logo"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to root_path do %>
            <i class="fa fa-home"></i>
            <%= t "static_pages.header.home" %>
          <% end %>
        </li>
        <li>
          <%= link_to help_path do %>
            <i class="fa fa-question-circle"></i>
            <%= t "static_pages.header.help" %>
          <% end %>
        </li>
        <% if logged_in? %>
          <li>
            <%= link_to users_path do %>
              <i class="fa fa-users"></i>
              <%= t "common.link_users" %>
            <% end %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-user"></i>
              <%= t "static_pages.header.account" %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to current_user do %>
                  <i class="fa fa-info-circle"></i>
                  <%= t "static_pages.header.link_profile" %>
                <% end %>
              </li>
              <li>
                <%= link_to edit_user_url current_user do %>
                  <i class="fa fa-gears"></i>
                  <%= t "static_pages.header.link_settings" %>
                <% end %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to logout_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>
                  <%= t "static_pages.header.log_out" %>
                <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to signup_path do %>
              <i class="fa fa-users"></i>
              <%= t "static_pages.header.sign_up" %>
            <% end %>
          </li>
          <li>
            <%= link_to login_path do %>
              <i class="fa fa-sign-in"></i>
              <%= t "static_pages.header.log_in" %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield :title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
    <script type="text/javascript">
      $(document).ready(function(){
        $('textarea').autosize();
      });
    </script>
  </body>
</html>